// <auto-generated />
using System;
using BakeryApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeryApp.Infrastructure.Migrations
{
    [DbContext(typeof(BakeryDbContext))]
    [Migration("20260908104739_InitialCreateFresh")]
    partial class InitialCreateFresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BakeryApp.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CommissionLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountEarned")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResellerEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerSaleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResellerId");

                    b.HasIndex("ResellerSaleId");

                    b.ToTable("CommissionLedgerEntries");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CommissionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("TierConfigurationJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("CommissionRules");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.DeliveryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActualDeliveryEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermanentDeliveryEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActualDeliveryEmployeeId");

                    b.HasIndex("PermanentDeliveryEmployeeId");

                    b.HasIndex("ResellerId");

                    b.ToTable("DeliveryAssignments");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.EmployeeId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResidenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("EmployeeIds");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.InventoryLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("InventoryLedgerEntries");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseCommissionAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ResellerSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommissionRuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResellerEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceAtSale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommissionRuleId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ResellerId");

                    b.ToTable("ResellerSales");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Residence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxResellerCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CommissionLedgerEntry", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Reseller")
                        .WithMany()
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.ResellerSale", "ResellerSale")
                        .WithMany()
                        .HasForeignKey("ResellerSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reseller");

                    b.Navigation("ResellerSale");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CommissionRule", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.DeliveryAssignment", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "ActualDeliveryEmployee")
                        .WithMany()
                        .HasForeignKey("ActualDeliveryEmployeeId");

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "PermanentDeliveryEmployee")
                        .WithMany()
                        .HasForeignKey("PermanentDeliveryEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Reseller")
                        .WithMany()
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualDeliveryEmployee");

                    b.Navigation("PermanentDeliveryEmployee");

                    b.Navigation("Reseller");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.EmployeeId", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.Person", "Person")
                        .WithMany("EmployeeIds")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.Residence", "Residence")
                        .WithMany("AssignedResellers")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.InventoryLedgerEntry", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("BakeryApp.Core.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ProductVariant", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ResellerSale", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.CommissionRule", "CommissionRule")
                        .WithMany()
                        .HasForeignKey("CommissionRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Reseller")
                        .WithMany()
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionRule");

                    b.Navigation("ProductVariant");

                    b.Navigation("Reseller");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Person", b =>
                {
                    b.Navigation("EmployeeIds");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Residence", b =>
                {
                    b.Navigation("AssignedResellers");
                });
#pragma warning restore 612, 618
        }
    }
}
