// <auto-generated />
using System;
using BakeryApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeryApp.Infrastructure.Migrations
{
    [DbContext(typeof(BakeryDbContext))]
    partial class BakeryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BakeryApp.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.BuyerOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BuyerOrders");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CashCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CollectedAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeliveryEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReconciledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReconciledByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Variance")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarianceNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("VarianceReason")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryEmployeeId");

                    b.HasIndex("ReconciledByAdminId");

                    b.ToTable("CashCollections");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CommissionLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountEarned")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResellerEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerSaleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResellerId");

                    b.HasIndex("ResellerSaleId");

                    b.ToTable("CommissionLedgerEntries");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CommissionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("TierConfigurationJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("CommissionRules");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.DeliveryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActualDeliveryEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermanentDeliveryEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActualDeliveryEmployeeId");

                    b.HasIndex("PermanentDeliveryEmployeeId");

                    b.HasIndex("ResellerId");

                    b.ToTable("DeliveryAssignments");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.DeliveryEarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountEarned")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeliveryAssignmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeliveryEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarningDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryAssignmentId");

                    b.HasIndex("DeliveryEmployeeId");

                    b.ToTable("DeliveryEarnings");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankReference")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeliveryEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepositDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofMimeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CashCollectionId");

                    b.HasIndex("DeliveryEmployeeId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.EmployeeId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResidenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("EmployeeIds");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.InventoryLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("InventoryLedgerEntries");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseCommissionAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ResellerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedResidencePopulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedTimeAtResidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredSellingArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSalesExperience")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResidenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidenceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedEmployeeId");

                    b.HasIndex("ResidenceId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("ResellerApplications");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ResellerSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommissionRuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResellerEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceAtSale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommissionRuleId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ResellerId");

                    b.ToTable("ResellerSales");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ResellerStockRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AllocatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AllocatedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InventoryLedgerEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResellerEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResellerNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ResellerId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("ResellerStockRequests");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Residence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxResellerCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CashCollection", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "DeliveryEmployee")
                        .WithMany()
                        .HasForeignKey("DeliveryEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "ReconciledByAdmin")
                        .WithMany()
                        .HasForeignKey("ReconciledByAdminId");

                    b.Navigation("DeliveryEmployee");

                    b.Navigation("ReconciledByAdmin");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CommissionLedgerEntry", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Reseller")
                        .WithMany()
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.ResellerSale", "ResellerSale")
                        .WithMany()
                        .HasForeignKey("ResellerSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reseller");

                    b.Navigation("ResellerSale");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.CommissionRule", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.DeliveryAssignment", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "ActualDeliveryEmployee")
                        .WithMany()
                        .HasForeignKey("ActualDeliveryEmployeeId");

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "PermanentDeliveryEmployee")
                        .WithMany()
                        .HasForeignKey("PermanentDeliveryEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Reseller")
                        .WithMany()
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualDeliveryEmployee");

                    b.Navigation("PermanentDeliveryEmployee");

                    b.Navigation("Reseller");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.DeliveryEarning", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.DeliveryAssignment", "DeliveryAssignment")
                        .WithMany()
                        .HasForeignKey("DeliveryAssignmentId");

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "DeliveryEmployee")
                        .WithMany()
                        .HasForeignKey("DeliveryEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryAssignment");

                    b.Navigation("DeliveryEmployee");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Deposit", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.CashCollection", "CashCollection")
                        .WithMany()
                        .HasForeignKey("CashCollectionId");

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "DeliveryEmployee")
                        .WithMany()
                        .HasForeignKey("DeliveryEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId");

                    b.Navigation("CashCollection");

                    b.Navigation("DeliveryEmployee");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.EmployeeId", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.Person", "Person")
                        .WithMany("EmployeeIds")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.Residence", "Residence")
                        .WithMany("AssignedResellers")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.InventoryLedgerEntry", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("BakeryApp.Core.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.BuyerOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ProductVariant", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ResellerApplication", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "ApprovedEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedEmployeeId");

                    b.HasOne("BakeryApp.Core.Entities.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId");

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId");

                    b.Navigation("ApprovedEmployee");

                    b.Navigation("Residence");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ResellerSale", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.CommissionRule", "CommissionRule")
                        .WithMany()
                        .HasForeignKey("CommissionRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Reseller")
                        .WithMany()
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionRule");

                    b.Navigation("ProductVariant");

                    b.Navigation("Reseller");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.ResellerStockRequest", b =>
                {
                    b.HasOne("BakeryApp.Core.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "Reseller")
                        .WithMany()
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Core.Entities.EmployeeId", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId");

                    b.Navigation("ProductVariant");

                    b.Navigation("Reseller");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.BuyerOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Person", b =>
                {
                    b.Navigation("EmployeeIds");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("BakeryApp.Core.Entities.Residence", b =>
                {
                    b.Navigation("AssignedResellers");
                });
#pragma warning restore 612, 618
        }
    }
}
